source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'puma'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'simple_form'
gem 'client_side_validations'
gem 'devise'
gem 'binding_of_caller'
gem 'carrierwave'
gem 'mini_magick'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'better_errors'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
 gem 'rb-fsevent', '~> 0.9'
 gem 'rspec-rails'
 gem 'shoulda'
 gem 'shoulda-matchers'
 gem 'factory_girl_rails', :require => false
 gem 'capybara'
 gem 'launchy'
 gem 'database_cleaner'
 gem 'guard'
 gem 'guard-rspec'
 gem 'faker'
 gem 'quiet_assets'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'debugger'
